name: Deploy Go Application

on:
    push:
        branches:
          - master

jobs:
    build:
        runs-on: ubuntu-latest 
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4       
            - name: Login to Docker Hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}      
            - name: Build Docker image
              run: docker build -t muhammadandres/manajementugasapp .          
            - name: Push image to Docker Hub
              run: docker push muhammadandres/manajementugasapp:latest
    
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}
            - name: Install AWS CLI v2
              run: |
                sudo apt-get update && sudo apt-get install -y unzip
                curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                unzip -o awscliv2.zip
                sudo ./aws/install --update
              shell: bash
            - name: Pull Docker image
              run: docker pull muhammadandres/manajementugasapp:latest        
            - name: Delete old container
              run: docker rm -f manajemen-tugas-container || true
            - name: Run Docker container
              env:
                PORT: ${{ secrets.PORT }}
                DB_URL: ${{ secrets.DB_URL }}
                SECRET: ${{ secrets.SECRET }}
                AWS_REGION: ${{ secrets.AWS_REGION }}
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                DB_HOST: ${{ secrets.DB_HOST }}
                DB_USER: ${{ secrets.DB_USER }}
                DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                DB_NAME: ${{ secrets.DB_NAME }}
                GOOGLE_CALENDAR_CREDENTIALS: ${{ secrets.GOOGLE_CALENDAR_CREDENTIALS }}
                CLIENT_ID: ${{ secrets.CLIENT_ID }}
                CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
                REDIRECT_URL: ${{ secrets.REDIRECT_URL }}
              run: |
                docker run -d -p 4040:4040 --name manajemen-tugas-container \
                  -e PORT -e DB_URL -e SECRET -e AWS_REGION -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY \
                  -e DB_HOST -e DB_USER -e DB_PASSWORD -e DB_NAME \
                  -e GOOGLE_CALENDAR_CREDENTIALS \
                  -e CLIENT_ID -e CLIENT_SECRET -e REDIRECT_URL \
                  muhammadandres/manajementugasapp:latest