name: Deploy Go Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo 'PORT=${{ secrets.PORT }}' >> .env
          echo 'DB_URL=${{ secrets.DB_URL }}' >> .env
          echo 'SECRET=${{ secrets.SECRET }}' >> .env
          echo 'AWS_REGION=${{ secrets.AWS_REGION }}' >> .env
          echo 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}' >> .env
          echo 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}' >> .env
          
      - name: Create credentials.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CALENDAR_CREDENTIALS }}
        run: echo "$GOOGLE_CREDENTIALS" > credentials.json

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: muhammadandres/manajementugas:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Pull latest Docker image
        run: docker pull muhammadandres/manajementugas:latest

      - name: Stop and remove old container
        run: docker rm -f manajemen-tugas-container || true

      - name: Run Docker container
        env:
          PORT: ${{ secrets.PORT }}
          DB_URL: ${{ secrets.DB_URL }}
          SECRET: ${{ secrets.SECRET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          docker run -d \
            --name manajemen-tugas-container \
            -p 4040:4040 \
            -e PORT=$PORT \
            -e DB_URL=$DB_URL \
            -e SECRET=$SECRET \
            -e AWS_REGION=$AWS_REGION \
            -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
            -e DB_HOST=$DB_HOST \
            -e DB_USER=$DB_USER \
            -e DB_PASSWORD=$DB_PASSWORD \
            -e DB_NAME=$DB_NAME \
            muhammadandres/manajementugas:latest

      - name: Check container logs
        run: docker logs manajemen-tugas-container

      - name: Verify application health
        run: |
          for i in {1..5}; do
            if curl -sSf http://localhost:4040/health; then
              echo "Application is healthy"
              exit 0
            fi
            echo "Waiting for application to become healthy..."
            sleep 10
          done
          echo "Application failed to become healthy"
          exit 1